# Generated by Django 3.2.4 on 2021-06-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URLID', models.CharField(max_length=1000)),
                ('CondensedURL', models.CharField(max_length=1000)),
            ],
        ),
    ]
